# 산포통계

In [2]:
import numpy as np
from scipy import stats
import pandas as pd

## 분산 계산

In [ ]:
x = [1, 2, 3, 4, 5]
# ddof Delta Degrees of Freedom -> 자유도 조정값 
# "표준편차를 계산할 때 분모에서 몇을 뺄 것인가?"
# ddof=1은 분모를 N이 아니라 N-1로 하라는 의미

# var = 분산(Variance)
print(np.var(x, ddof = 1)) # 분모 = n - 1 ( 5 - 1), 표본
print(np.array(x).var()) # 분모 = n
# 분모 = n , 자유도(ddof) 0:모분산인경우, 표본분산
# Series : Pandas의 1차원 데이터 구조
print(pd.Series(x).var(ddof = 0))

2.5
2.0
2.0

## 표준편차 계산

In [ ]:
x = [1, 2, 3, 4, 5]
# std는 Standard Deviation(표준편차)
print(np.std(x, ddof = 1))
print(np.array(x).std(ddof = 0))
print(pd.Series(x).std(ddof = 1))

1.5811388300841898
1.4142135623730951
1.5811388300841898

## 변동계수의 필요성

- 분산과 표준편차 모두 값의 스케일에 크게 영향을 받아 상대적인 산포를 보여주는데 부작합함.
- 변동 계수 = 표준편차 / 평균

In [20]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

print(np.std(x1,ddof = 1))
print(np.std(x2,ddof=1))

1.5811388300841898
15.811388300841896

In [7]:
print(stats.variation(x1)) # 변동 계수
print(stats.variation(x2))

0.47140452079103173
0.4714045207910317

In [8]:
print(np.std(x1, ddof = 1) / np.mean(x1))
print(np.std(x2, ddof = 1) / np.mean(x2))

0.5270462766947299
0.5270462766947299

## 스케일링
- 둘 이상의 변수의 값을 상대적으로 비교할 때 사용

In [9]:
import numpy as np
import pandas as pd

In [10]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

In [11]:
x1

array([1, 2, 3, 4, 5])

In [12]:
x2

array([10, 20, 30, 40, 50])

In [ ]:
# Standard Scaling
# 평균을 0, 표준편차를 1로 변환하는 전처리 방법
z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 - x2.mean()) / x2.std()

print(z1)
print(z2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [ ]:
# Min-max Scaling
# 0~1 사이로 변환
z1 = (x1 - x1.min()) / (x1.max() - x1.min())
z2 = (x2 - x2.min()) / (x2.max() - x2.min())

print(z1)
print(z2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]

In [ ]:
# sklearn을 이용한 스케일링을 위한 데이터 준비
# 표 형태
# DataFrame은 Pandas에서 사용하는 2차원 표 형태의 데이터 구조라서
X = pd.DataFrame({"X1":[1, 2, 3, 4, 5],
    "X2": [10, 20, 30, 40, 50]})

X

   X1  X2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [ ]:
# scikit learn 의 MinMaxScaler 적용
# 0 ~ 1 데이터 스크케일링함
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # 인스턴스화
# fit_transform(X)은 X의 스케일링 기준을 학습(fit)한 후, 그 기준으로 X를 변환(transform)하는 함수이다.
Z = scaler.fit_transform(X) # fit_transform => ndarray

pd.DataFrame(Z, columns=['X1', 'X2'])

     X1    X2
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

In [17]:
# 표준 정규분포에 따라서 데이터의 수준을 맞춤
# 표준 정규분포 : 
from sklearn.preprocessing import StandardScaler

In [18]:
ss_scaler = StandardScaler() # 인스턴스화
Z = ss_scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(Z, columns=['X1', 'X2'])

         X1        X2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

In [19]:
# Standard scaling
from sklearn.preprocessing import StandardScaler

ss_scaler = StandardScaler() # 인스턴스화
S = ss_scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(S, columns=['X1', 'X2'])

         X1        X2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

범위와 사분위 범위 계산

- 정규분포(np.random.normal)로 부터 무작위 샘플 만들기

- np.random.normal(0,1,1000) # [정규분포] 평균 0, 표준편차 1, 개수 1000개

In [23]:
# np.random.normal(평균, 편차, size = 갯수)
x = np.random.normal(100, 20, size = 1000)
x

array([ 75.91145656,  71.53392335,  89.36416767, 118.56181468,
        80.82459478, 107.77515856,  73.10729414, 104.95568397,
       118.9175684 , 130.22560804, 124.08015823,  88.54605055,
       129.15620175, 117.47308696, 144.03818413, 101.8795811 ,
       115.5075401 ,  82.34638639, 101.43291143, 137.82301448,
       102.23060916, 104.95330656, 101.31498966,  55.69222818,
       117.54643249, 107.1169438 , 111.13885792,  97.7952974 ,
       110.23710668, 107.34976447, 125.39060618,  72.18639115,
       100.6268425 ,  89.2287994 , 103.48080081,  93.11724944,
        77.24984301, 100.06581015,  88.94254625,  94.32475056,
       103.60255384, 126.06484776,  56.23619008,  92.32170175,
       114.37508963, 120.81858045,  80.10743758, 120.28939159,
       113.7459277 , 100.00191493,  73.16384677,  96.69395616,
        99.77307308,  81.93065813,  98.60363557,  89.18940223,
        97.84099691, 119.3331161 ,  86.9450761 , 103.67426634,
        93.64566478, 102.22646739,  88.93568101,  74.28116222,
       121.2708487 ,  91.23122043, 112.90358155,  95.3263445 ,
       112.79201179,  79.64632624, 105.32346599, 132.95414435,
        83.45498746,  76.8061811 ,  98.11203822,  91.13247546,
        99.82202585,  88.4697785 ,  83.08720244, 158.76697743,
        92.31928669, 123.87740192, 152.30955134,  91.82265167,
       110.4156935 , 137.99812135,  93.61243925,  95.0902072 ,
       118.50022553, 105.91497594,  55.28757995, 123.68814443,
        84.03716269, 119.62896696, 124.1532461 ,  69.38587126,
        86.07230361,  70.09131274, 101.79634731,  99.45825516,
       128.44873856,  78.16106739,  93.35421736, 107.33869458,
       131.98008828, 103.46960523,  81.64099655, 125.26562235,
       127.23097309, 110.71476098, 117.27899407,  87.42762189,
        78.09365608, 123.87404283,  73.4665986 ,  91.94329675,
       107.56122859, 107.27116868,  88.82265359,  88.41964246,
       136.78963886, 102.36254436,  80.49016494, 135.27533165,
       101.57877769, 109.26944142, 102.12673935,  77.69910385,
        88.57617236, 154.98299453,  91.42578462,  67.66529317,
       144.49700089, 109.34925341,  69.56978044,  66.21383449,
       106.78182124, 113.01103416,  81.68423887,  97.86394549,
       113.66737612,  66.16954899,  88.53952835, 134.04678197,
       118.59524883, 116.63580521, 138.02076519, 102.27129274,
       108.85919394,  77.11985601,  84.05929994, 137.04686459,
        41.09112261,  55.70613644,  96.54339852, 114.73013814,
       133.9771722 , 124.79547235,  91.64790843, 111.34872086,
        84.06569275, 100.30126334,  92.8651744 , 117.53406496,
       109.70515823,  96.12323903, 132.54828039,  77.59450648,
        90.28844489, 119.5159195 ,  83.29263764, 119.16297774,
        78.0640659 , 120.35189678, 115.86884737,  90.15173327,
       115.97545994, 119.72124951,  87.86700405,  90.31103906,
       130.91361208, 115.9329778 , 107.21133982,  79.40634698,
        93.42640689, 103.8104817 , 102.47321155, 112.91276994,
        84.928591  ,  88.62163948,  99.46332239, 119.67489934,
       114.29715252,  70.88401106, 121.61354933, 115.45811768,
        75.1303229 ,  64.731751  , 107.90691975,  91.13184503,
       115.90148446,  92.08638923, 110.96565868, 112.32587643,
        78.11983681, 103.99885623,  88.74128474, 105.29717273,
        95.93518715, 128.33517589,  78.23456094,  78.45460359,
       134.54768822,  64.58509348, 109.44536522, 105.51972641,
       137.54455492, 129.09484298,  57.20239162,  80.04408213,
        75.23904767,  92.02584701, 116.60023449, 136.01115791,
       134.70150255, 136.44050526,  76.48080887,  81.45178575,
       102.74516916, 103.33056601,  82.11245963, 133.32100024,
        60.79416031, 139.82808473, 100.95585359,  69.59720187,
       127.80713969,  94.79326682, 104.69453964,  63.5328716 ,
       100.94615119,  84.88670123, 111.73850087, 138.84263826,
       115.89882014,  94.16635037,  65.79650494,  73.56464928,
        72.30163406,  90.92207878,  90.42247927,  95.86023055,
        99.28971208,  73.32309477,  91.01826542,  93.1521755 ,
       124.67324591,  98.27314806,  93.54236572, 108.73283155,
       125.9871065 ,  89.67753312, 102.37455959, 104.47682013,
       118.19455293, 104.78775224, 114.93194086,  53.33969704,
       103.48658969, 130.70610005,  94.6058827 , 102.70063504,
       120.81627549,  96.47472604, 116.43242339, 107.22870602,
        89.71009585,  88.49233939, 103.12422969, 100.82837526,
       118.07100136, 118.49047691,  97.63134526,  69.10672971,
        93.41905655, 132.44554389,  95.67792066, 107.72405502,
        81.94656742,  74.02747497, 111.26968076,  69.38837129,
       135.42951402,  98.90947679, 129.82800042, 111.56630782,
        99.44673384,  92.76613654, 119.30722119, 109.75071191,
        93.45227306, 116.58980304,  90.22384997,  88.00700499,
       120.87691894,  82.02051798, 113.08765616,  88.54330384,
        69.20006162,  90.65305058, 121.84255895,  99.51322731,
       106.77717381,  65.90878374,  69.97545591,  91.35796614,
        52.18504294,  63.85442605, 100.26361649, 128.75664108,
        99.61537782,  78.72403712,  96.39143671,  75.61065986,
        80.72099222, 102.17353488,  85.10191607,  80.15604259,
        83.89350686, 112.91475138,  87.08484309, 115.09318812,
        89.48473034, 118.73454896,  98.36743093, 110.7703956 ,
        74.65654299,  74.25254026,  95.5960928 ,  89.83974042,
        82.15420283, 105.2420478 ,  57.02329576, 120.37721217,
       110.4842148 , 120.3516154 ,  87.39088294, 114.62443356,
       108.06933185, 123.70822236,  93.41306153,  82.25856032,
       113.62301091, 109.96536607, 116.43981641, 111.65022776,
        40.58043565, 122.83517504, 114.88407857, 127.83102933,
       126.84351599,  72.11452318,  99.38724273, 113.51396758,
       120.35115959,  85.62786333,  53.94228075, 106.91237605,
       111.46418822, 111.87780774,  90.75533797,  96.86911335,
        96.88348465, 102.12800025,  58.37700991,  82.56853028,
       116.6492565 ,  96.83303536,  93.32552446, 107.43427465,
       118.34090231, 134.23867029,  92.11377618, 103.90312097,
        93.92028005, 108.68723965,  88.38851597, 132.12855846,
       107.30071061,  86.88340472, 100.19427999, 112.81964356,
        59.17778782, 106.25455439,  99.32924314,  64.39609347,
        92.28580548, 110.68112398, 113.05888133,  91.04694541,
       126.57850978, 110.11279347,  92.23128783,  92.38138056,
       130.20283494, 119.2084815 ,  89.90574269, 135.11494888,
        90.37068479, 131.78345136, 136.91430887,  94.505446  ,
       123.22763037,  93.97876207, 126.36197618,  98.35543426,
       131.45562773, 121.0876531 ,  74.99769904, 124.83288878,
        92.0010875 , 101.97110254, 126.53653354, 117.79331885,
       129.78923963, 109.4947712 ,  84.23387398, 110.82272826,
        92.54052443,  78.60319428, 101.08840796, 120.50529842,
       101.61282149, 100.8368246 ,  53.37924221, 109.75288944,
       116.8432169 , 105.41185881, 109.32700663, 117.94179523,
       112.09611195, 156.02824315, 103.35543257,  93.47246177,
       105.13302938,  93.19704744,  87.94265166, 111.3060012 ,
       102.79158936,  93.47943543,  75.48281971, 122.36509286,
       106.84400409,  88.447873  , 103.94469589,  81.06619033,
       101.03626711,  83.92215189,  65.68952812, 107.33307988,
       109.31578529,  62.75070232, 109.32576488, 107.65653618,
       136.88539666, 107.51634442, 144.68768943, 122.92800339,
       101.60083628,  82.37240311, 124.20972757, 101.24646719,
        99.20118548,  97.96581726, 113.97356084, 102.27711952,
        93.69324126, 136.66411928,  96.14261304, 106.89629776,
       101.21522779,  92.65591614, 139.84222957, 144.66139568,
        70.11326064, 109.51529951, 104.93794606, 109.36494624,
        93.21251771, 110.62902687,  90.53252465, 102.96011429,
       118.27258315, 104.32953147, 109.64919024,  88.20418527,
        87.81898968,  85.42773331, 111.12124932,  90.88477617,
       101.01649475,  72.70001306,  84.22137107, 110.63060498,
        75.68593758, 106.54308714,  77.19505827, 133.83352176,
       126.70406134,  95.64446656, 122.51597638,  95.40240778,
       100.50782145,  91.91690496,  93.31458436,  86.37606541,
       102.34878733, 108.35766825, 110.45363022,  98.14923839,
        96.15280537, 104.54877527,  94.85395935,  98.49913074,
       104.77104569, 106.53982926, 107.05738521, 108.21898644,
       120.17652923,  94.28773532,  84.35865736,  84.82368277,
       124.29828899, 129.13832196,  62.71154078,  73.10216449,
        69.31020458,  74.29140996, 110.14568984,  68.51309066,
       128.3071377 ,  87.58095536,  84.95783489,  74.17527051,
       108.75684037, 124.07435889,  90.50500423, 105.33370735,
       119.66901016,  98.18297343, 131.72650326, 120.06501631,
       113.84753649, 100.1805721 ,  98.16886207,  88.23557454,
        83.02653567,  82.82001608,  85.66663067, 112.09303236,
       103.1179391 ,  79.49435085,  78.62315737, 143.88006505,
       111.29375315, 116.27142143, 103.22335898,  78.00901355,
        87.34706872, 120.57156724,  86.6031841 ,  81.96135244,
        79.17226333, 128.73542065,  72.36791024, 102.77815588,
       117.57565311,  81.70649039, 118.31025178, 100.52897968,
       106.29255448, 107.11440258, 122.08442237, 126.09642989,
        95.11804222,  78.16316896, 107.43352531, 114.39067439,
       104.76330014,  74.521992  ,  82.11952847,  86.70828572,
        99.43798761,  90.87506716, 101.31514056, 103.41462763,
       126.758424  ,  84.44083331, 108.61410399,  72.98275201,
       100.76069107, 112.78428558,  86.71858447, 106.04984761,
        77.52685308, 103.648823  ,  72.00656551,  97.5712867 ,
        60.3836279 , 133.24833635,  82.26773135,  83.64582356,
        86.82190435, 111.44193313, 115.30502472,  93.76598436,
       109.34279008,  95.46303016, 109.33906485, 116.29390141,
        84.79604919, 107.22222695,  92.81420199,  97.78648799,
       141.85949998, 101.73061723, 110.55490766, 116.47699549,
        54.05838195, 111.09644764, 128.09379155, 108.20744737,
       110.16977564,  84.45059852,  83.46667573, 115.20307593,
       109.7955541 , 103.5366077 , 100.99053762, 120.42405332,
        74.93755959,  82.77824368, 124.27952391,  87.20312873,
        88.82275925,  86.13361903,  88.70090949,  72.93191029,
       100.57102758,  92.88189061, 134.86822609,  94.5282492 ,
        79.63471106,  63.65439389,  70.94701062, 118.95858887,
        77.90115895,  97.46534704,  73.39988871,  95.11984448,
       142.33505526, 105.33919266,  97.11589708, 106.06673384,
       146.94455395, 101.90994528, 116.45778031,  90.48370131,
        86.47658522, 116.99324969, 128.32346177,  79.91113106,
       134.68813836,  81.03417944,  95.85862611, 118.25669415,
       137.63930712,  77.85498907, 117.26095534, 110.72876876,
       105.19083316, 104.36752836, 122.21778832,  72.68826363,
       125.4102754 , 108.25579986, 104.29497356,  83.16732522,
       128.68869691, 104.07029143,  81.26098214, 115.05865474,
       114.76719849,  90.59951533,  94.14713369,  76.61845958,
        94.23909915, 111.97353449,  97.33725193,  97.96128937,
       100.15131392,  56.44993954, 104.82296613,  69.73101437,
       116.70034521,  94.39050821, 122.90819914, 126.5790824 ,
       130.13909629,  89.89957292, 106.9062647 ,  81.94665752,
       111.4668639 , 105.5202904 , 116.24039497,  90.50209712,
        87.06234915, 104.72619876,  92.06249993, 100.02061385,
       119.3823466 , 110.86271325,  88.08314532, 111.69295191,
       138.534803  ,  95.46073287, 105.79203562,  85.89494311,
        61.02372377,  96.28195843, 105.8782678 , 119.51590398,
        85.99331307,  85.86235895, 117.63989629, 140.46889767,
       149.13401788, 100.23750249, 127.89415773, 123.83524311,
       111.91104006, 115.57440079, 108.75771311, 100.90906097,
       112.20312589, 108.1744719 , 110.11452851, 115.81689429,
        98.96025823,  94.95076003,  91.25284462, 102.04799159,
        86.54451239,  80.6099164 ,  87.36430138,  72.81632759,
        63.09898129,  54.49457504,  97.99796515, 148.41383661,
       105.07349411, 102.21142095, 110.90127438,  61.96850838,
        99.92975236, 116.48831212, 100.30143904, 121.14183099,
        90.30986908,  95.55628277, 113.20759763,  94.55116415,
       120.61988926,  75.85478867, 106.55234271, 103.66919822,
       109.51188481,  97.53470416,  89.04822063,  97.01784895,
        61.9670429 ,  97.11350996, 101.83930163,  93.80849342,
        74.27183687,  70.47297033, 101.64512194, 115.6005156 ,
       106.09958058, 120.31138102,  68.06954279, 116.54691122,
        70.39148405,  96.18804671, 134.89453957,  84.08056595,
       110.52772375, 100.19534684,  56.43505061, 129.23417195,
       113.17238014,  97.53834797, 101.26163835,  94.0241832 ,
        72.03296461, 126.66090435,  77.90036548, 119.07024233,
       127.92703531, 116.75261586,  80.41768936, 137.65666179,
       115.45177199, 128.05424165, 125.22441549,  65.80105494,
        91.72081615, 104.23028425, 107.34997665, 102.53756631,
        89.55631421,  82.96891629, 118.31771023, 105.05693997,
        58.21899533, 136.96671624,  91.24976639,  95.2993553 ,
        95.27163248, 107.74346689,  59.95596968,  93.70800494,
        93.26298624, 106.57399931,  83.69249578,  97.17891471,
        66.40454789, 103.14488063,  55.06885713, 119.51481837,
        89.08302447, 106.35049506,  84.04043495,  87.41043385,
        92.53654202,  64.30380792,  88.60814844,  81.7008783 ,
       127.40713578, 106.57682544,  94.06843379,  69.67039486,
        88.76927831, 113.88435021, 105.97505588,  95.95460818,
        78.8742594 ,  49.7060063 , 124.97077389,  83.44130768,
       117.41643158,  99.37830562, 123.2904413 , 110.25708675,
       107.347536  , 126.1471337 , 124.15672044,  90.77147848,
        99.55553009,  89.12294294, 144.29463606,  88.38643458,
        97.41855625, 133.59621065, 101.23086572,  82.41590383,
       103.31303279, 129.05679918,  92.92008986,  96.41485009,
        68.24453991, 123.00784962, 108.4020358 , 104.63260812,
        72.89481691, 113.84007622,  86.80054736,  80.77124974,
        67.06336451, 109.18086175,  92.33932831, 102.40170764,
       108.04132548, 101.56619913,  74.3988607 ,  56.48250429,
        88.149317  , 110.3286359 , 126.6368717 , 131.90483544,
       114.5551001 ,  74.33191197,  78.07469467, 100.44534773,
       102.39152675,  87.07762324,  99.63889667,  66.53309914,
       106.89838861, 113.0793406 ,  81.03796497,  51.21975351,
       121.76472294,  88.64738578, 103.7317768 , 111.67872781,
       107.45345111,  69.48042412,  90.7987976 , 107.58064643,
       113.27798635,  94.114387  , 140.74461367,  95.60169729,
       111.26802204,  94.2642045 , 134.83009584, 147.18151844,
        80.53987047, 107.08624731, 102.00433727, 119.62670697,
       123.00145849,  84.40577288,  92.09032121,  73.19175475,
        99.38262676, 114.57229548, 101.41238473,  98.75991375,
        59.75563299,  87.83011426,  92.73854769,  99.00656738,
        90.26807507, 120.65635749,  65.83288967, 109.09536144,
        62.15456299,  92.02271694, 116.55375927, 103.71000364,
        91.89797269,  77.87908412,  95.8190583 , 113.32785382,
       109.94545256,  75.64003043,  77.82095147, 111.26772018,
       133.86252448,  73.73007927, 102.31703158,  92.77305831,
        91.15114522, 114.48515044,  86.48134493,  87.77193613,
        90.3242158 ,  85.80393096,  80.6891411 , 106.97615425,
       113.7154376 , 113.97429655,  81.16608801, 100.42115455,
       110.02834639, 122.86546073,  98.97510799, 111.88767572,
       104.4190246 ,  55.63360053,  84.63570768, 101.93364642,
       126.06410337, 118.64997803,  84.28174084, 127.77687415,
       136.00027538,  64.34923808, 110.35954763,  86.97529258,
       115.03065402,  90.52833255, 112.53450159, 109.75049985,
        88.68922668, 123.83528372, 103.16929909,  59.06080067])

In [24]:
print(np.ptp(x))
print(np.max(x) - np.min(x))

118.18654178769334
118.18654178769334

In [25]:
print(np.quantile(x, 0.75) - np.quantile(x, 0.25))
print(stats.iqr(x))

25.91583383592878
25.915833835928765